steps:

- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/lunch-and-learn:$SHORT_SHA'
  - './source/docker/'


- name: 'gcr.io/cloud-builders/docker'
  id: Push
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/lunch-and-learn:$SHORT_SHA'

