apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  labels:
    customer: acg
spec:
  selector:
    matchLabels:
      app: web
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - image: gcr.io/store-controller/lunch-and-learn:100.100.100.3
        name: lunch-and-learn
        imagePullPolicy: Always
        ports:
        - containerPort: 8080